const mongoose = require('mongoose');
const {Schema} = mongoose;
const problemSchema=new Schema({
   title:{
      type:String,
      required:true,
      maxLength:100
   },
   description:{
      type:String,
      required:true,
      minLength:10,
   },
   difficulty:{
      type:String,
      enum:['easy','medium','hard'],
      required:true
   },
   tags:{
      type:[String],
      enum:['array','linkedList','tree','graph','dynamicProgramming','greedy','backtracking','sorting','searching','twoPointer','string','stack'],
      required:true
   },
   visibleTestCases:[{
      input:{
         type:String,
         required:true,
      },
      output:{
         type:String,
         required:true,
      },
      explanation:{
         type:String,
         required:true,
      }
   }],
   hiddenTestCases:[{
      input:{
         type:String,
         required:true,
      },
      output:{
         type:String,
         required:true,
      }
   }],
   startCode:[{
      language:{
         type:String,
         required:true
      },
      initialCode:{
         type:String,
         required:true
      }
   }],
   referenceSol:[{  
      language:{
         type:String,
         required:true
      },
      Code:{
         type:String,
         required:true
      }
   }],
   judgeWrapperCode:[{  
      language:{
         type:String,
         required:true
      },
      Code:{
         type:String,
         required:true
      }
   }],
   problemCreator:{
      type:Schema.Types.ObjectId,
      ref:'User',
      required:true
   }
},{
   timestamps:true,
})

const Problem=mongoose.model('problem',problemSchema);
module.exports=Problem;